export enum DATE_FORMAT {
    DATE_ONLY = 'DD/MM/YYYY',
    FULL = 'HH:mm:ss DD/MM/YYYY',
    DATE_MINUTE = 'HH:mm DD/MM/YYYY',
    MONTH_YEAR = 'MM/YYYY',
    YEAR = 'YYYY',
    DATE_ONLY_REVERSE = 'YYYY/MM/DD',
    MYSQL_TYPE_DATE = 'YYYY-MM-DD',
    REPORT = 'MMMM DD, YYYY',
    DATE_MONTH = 'DD/MM',
    HOUR_MINUTE = 'HH:mm:ss',
    YEAR_MONTH_DAY_TIME = 'YYYY-MM-DD HH:mm:ss',
}